<?php

namespace AppBundle\Repository;

/**
 * AdRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAdWithPriceGreaterThanPrice($price)
    {
        $dql= <<<DQL
SELECT a
FROM AppBundle:Ad a
WHERE a.price >=:price
DQL;

    return $this
        ->getEntityManager()
        ->createQuery($dql)
        ->setParameter('price', $price)
        ->getResult();
    }

    public function findAdCategory($motcle)
    {
        $dql = <<<DQL
SELECT a, c
FROM AppBundle:Ad a
LEFT JOIN a.category c 
WHERE a.title LIKE :motcle OR a.description LIKE :motcle OR c.name LIKE :motcle
DQL;
        return $this
            ->getEntityManager()
            ->createQuery($dql)
            ->setParameter('motcle','%'.$motcle.'%')
            ->getResult();
    }

    public function findMyAd($id)
    {
        $dql = <<<DQL
SELECT a
FROM AppBundle:Ad a
WHERE a.user = :id
DQL;
            return $this
                ->getEntityManager()
                ->createQuery($dql)
                ->setParameter('id',$id)
                ->getResult();
    }

    public function findMyFavoriteAds($id)
    {
        $dql = <<<DQL
SELECT a
FROM AppBundle:Ad a
JOIN a.likersAds l
WHERE l.id = :id
DQL;
        return $this
            ->getEntityManager()
            ->createQuery($dql)
            ->setParameter('id', $id)
            ->getResult();
    }
}
