<?php

namespace AppBundle\Repository;

/**
 * AdRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAdWithPriceGreaterThanPrice($price)
    {
        $dql= <<<DQL
SELECT a
FROM AppBundle:Ad a
WHERE a.price >=:price
DQL;

        return $this
            ->getEntityManager()
            ->createQuery($dql)
            ->setParameter('price', $price)
            ->getResult();

    }
}
